defaults: &defaults
  google_id: "set in sec_config"
  google_secret:  "set in sec_config"
  not_a_secret: test

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults
