connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: workshops
  password: password

development:
  <<: *connection
  database: equinox_development

test: &test
  <<: *connection
  database: equinox_test